WIP Essi 474 m3 profile create and edit
notch8-old/essi pull request #22
Opened 2019-10-07 19:02 UTC by ShanaLMoore

GOAL: 
Extend 'New' M3 Profile to allow for creating a new profile from scratch (in addition to import ability)

DEMO: https://cl.ly/fe2445a9e650

**EXPECTATIONS**
MANUAL:

- [ ]  Create a M3Profile from scratch
- [ ]  There should not be a create button if profiles exist. Import button will always be present.
- [ ]  Classes MUST correspond to a Work Type in the repo ... provide a pick list for classes.
- [ ]  There is only ever one profile, it is versioned; versions cannot be edited
- [ ]  When the profile is edited we create a new version of the profile and of the associated contexts and dynamic_schemas

**ADDITIONAL NOTES**
IMPORT (blocked - dependent on essi-467):

2019-10-10 19:02 UTC, ghost requested changes

2019-10-10 19:02 UTC, ghost commented on app/models/m3/profile.rb
> +    validates :name, :responsibility, presence: true
I think these validates items got missed during rebase? could you re-instate?

2019-10-10 19:02 UTC, geekscruff commented on db/schema.rb
> +    t.integer "profile_version", default: 0
I think this is something I did, but we should put this back to float

2019-10-10 19:02 UTC, geekscruff commented on db/schema.rb
> +    t.integer "cardinality_minimum"
can we reinstate the defaults?

2019-10-10 19:02 UTC, geekscruff commented on db/migrate/20191007164507_add_default_version_to_m3_profiles.rb
> +class AddDefaultVersionToM3Profiles < ActiveRecord::Migration[5.1]
is this needed? (and the following) ... I'd been working on the basis that we'd drop and re-migrate during our sprint to avoid extra migrations

2019-10-10 23:29 UTC, ShanaLMoore commented on db/migrate/20191007164507_add_default_version_to_m3_profiles.rb
> +class AddDefaultVersionToM3Profiles < ActiveRecord::Migration[5.1]
remove migration file

2019-10-10 23:30 UTC, ShanaLMoore commented on app/models/m3/profile.rb
> +    validates :name, :responsibility, presence: true
reinstated

2019-10-10 23:31 UTC, ShanaLMoore commented on db/schema.rb
> +    t.integer "profile_version", default: 0
I blew away this schema as I think it's been quite mixed up and should get regenerated.

2019-10-10 23:36 UTC, ShanaLMoore commented on db/schema.rb
> +    t.integer "cardinality_minimum"
I blew away this schema as I think it's been quite mixed up and should get regenerated.

2019-10-11 09:59 UTC, ghost approved these changes

2019-10-11 10:00 UTC, merged