restrict m3 profile to admins only
notch8-old/essi pull request #8
Opened 2019-09-14 00:26 UTC by ShanaLMoore

@geekscruff Having a bit of trouble being able to easily utilize the user factory to create an admin in my specs. I have a workaround but feel that I shouldn't have to do it this way: https://notch8.slack.com/archives/CKY104K46/p1568418527000400

2019-09-16 14:28 UTC, ghost requested changes

2019-09-16 14:28 UTC, geekscruff commented on spec/models/ability_spec.rb
> +      it "should be manageable by a user of the buyer" do
tidy up the it description

2019-09-16 14:28 UTC, geekscruff commented on spec/models/ability_spec.rb
> +      it "should not be manageable by a user of the buyer" do
tidy up the it description

2019-09-16 14:28 UTC, geekscruff commented on spec/models/ability_spec.rb
> +    before { ability = Ability.new(user) }
I don't think this is needed, it will use the default from the top

2019-09-16 14:28 UTC, geekscruff commented on spec/models/ability_spec.rb
> +        user.roles << Role.where(name: 'admin').first_or_create
I couldn't figure out a way round this, would it be neater to put this line into a before block? (`before { user.roles << Role.where(name: 'admin').first_or_create }`)

2019-09-16 17:49 UTC, ShanaLMoore commented on spec/models/ability_spec.rb
> +      it "should not be manageable by a user of the buyer" do
oops, good catch. Apparently my mind is still over in Tangibol!

2019-09-16 17:52 UTC, ShanaLMoore commented on spec/models/ability_spec.rb
> +    before { ability = Ability.new(user) }
yep, I hadn't noticed that. Thanks!

2019-09-16 17:52 UTC, ShanaLMoore commented on spec/models/ability_spec.rb
> +      it "should be manageable by a user of the buyer" do
👍

2019-09-17 10:10 UTC, ghost approved these changes

2019-09-17 10:11 UTC, ghost reviewed
Nice!

2019-09-17 10:11 UTC, merged